# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Acesso Psicologia
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.acessopsicologia.com.br/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Copyright
copyright: © 2017 Acesso Psicologia - All rights reserved

# Jumbotron
jumbotron: 
  jumbotron_img: hero.jpg
  jumbotron_title: Amanda Silva de Moraes
  jumbotron_description: Psicóloga graduada em Psicologia pela Pontifícia Universidade Católica de Goiás. CRP 09/011111.

# Contacts
contact:
  phone: (62) 99958-5026
  email: amandademoraespsi@gmail.com
  address: Goiânia/GO - Brasil

# Opening hours
monday_friday: 09:00 - 21:00

# About
about:
  service: O serviço prestado consiste em atendimento psicológico via Skype.
  sessions: Os atendimentos são de caráter breve e focal (máximo de 20 sessões).
  price: O preço das sessões é combinado individualmente.
  elegibility: Menores de 18 anos precisam da autorização de seus responsáveis para que recebam atendimento.

# Secrecy
secrecy:
  title: Sigilo Profissional
  description: O profissional de psicologia tem a obrigação de guardar sigilo sobre os atendimentos. Sendo assim, é imprescindível que ambas partes (psicóloga e paciente) adotem medidas que diminuam os riscos e a vulnerabilidade dos atendimentos online (que não são absolutamente invioláveis).

# Faqs
faqs:
  - title: Código de Ética
    description: Código de ética do profissional psicólogo definido pelo Conselho Federal de Psicologia.
    link: http://site.cfp.org.br/wp-content/uploads/2012/07/codigo_etica.pdf
  
  - title: Resolução CFP N°011/2012
    description: Regulamenta os serviços psicológicos realizados por meios de comunicação a distância.
    link: http://site.cfp.org.br/wp-content/uploads/2012/07/Resoluxo_CFP_nx_011-12.pdf
  
  - title: CRP
    description: Site do Conselho Regional de Psicologia 9ª Região GO
    link: http://www.crp09.org.br/portal/index.php
  
  - title: CFP
    description: Site do Conselho Federal de Psicologia - Brasil
    link: http://site.cfp.org.br/

sass:
  sass_dir: _sass
  style: compressed